import pytest
import sqlite3
import datetime
from contextlib import contextmanager
from unittest.mock import patch
import pandas as pd
import numpy as np

from portfolio.ticker_period_ranks_data import (
    get_ndays_periods,
    df_overall_performance,
    df_secind_tick_perf,
    get_all_periods_ranked
)
from portfolio.portfolio_dashboard import app

@pytest.fixture
def mock_sqlite_db():
    conn = sqlite3.connect(':memory:')
    cursor = conn.cursor()
    
    # Create tables
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS market_data_close (
            date TEXT NOT NULL,
            ticker TEXT NOT NULL,
            close_price REAL NOT NULL,
            PRIMARY KEY (date, ticker)
        )
    """)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS ticker_meta_profile (
            ticker TEXT PRIMARY KEY NOT NULL,
            company_name TEXT,
            type TEXT,
            sector TEXT,
            industry TEXT
        )
    """)
    
    # Insert metadata
    cursor.executemany("""
        INSERT INTO ticker_meta_profile VALUES (?, ?, ?, ?, ?)
    """, [
        ('AAPL', 'Apple Inc.', 'EQUITY', 'Technology', 'Consumer Electronics'),
        ('MSFT', 'Microsoft Corp.', 'EQUITY', 'Technology', 'Software—Infrastructure')
    ])
    
    # Insert close prices for past 20 business days to cover all periods
    # We will generate dates using actual business day logic or mock dates.
    # Note: get_busdate_ndays_ago uses np.busday_offset relative to get_ny_now() (today).
    # To keep tests fully reproducible, let's insert close prices for the actual date strings
    # generated by get_busdate_ndays_ago.
    from portfolio.ticker_period_ranks_data import get_busdate_ndays_ago
    
    close_prices = []
    # Generate prices for 0 to 100 days ago to cover all period ranges
    for idx in range(100):
        dt_str = get_busdate_ndays_ago(idx)
        close_prices.append((dt_str, 'AAPL', 150.0 - idx * 0.5))
        close_prices.append((dt_str, 'MSFT', 300.0 - idx * 1.0))
        
    cursor.executemany("""
        INSERT INTO market_data_close VALUES (?, ?, ?)
    """, close_prices)
    
    conn.commit()

    @contextmanager
    def _get_conn():
        yield conn
        conn.commit()

    # Clear cache before each test
    from portfolio.ticker_period_ranks_data import global_cache
    global_cache['date'] = None
    global_cache['df_all_periods'] = None

    with patch('portfolio.ticker_period_ranks_data.get_sqlite_conn', _get_conn), \
         patch('database.database_utils.get_sqlite_conn', _get_conn), \
         patch('portfolio.portfolio_dashboard.get_sqlite_conn', _get_conn), \
         patch('portfolio.portfolio_dashboard.init_sqlite_db'), \
         patch('portfolio.ticker_period_ranks_data.get_tickers', return_value=['AAPL', 'MSFT']):
        yield conn
    conn.close()

def test_get_ndays_periods():
    periods = get_ndays_periods(months=[1])
    assert len(periods) > 0
    assert isinstance(periods, tuple)

def test_df_overall_performance(mock_sqlite_db):
    ndays_range = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
    df = df_overall_performance(ndays_range, ['AAPL', 'MSFT'])
    assert len(df) == 2
    assert 'over_pc' in df.columns
    assert 'pc_mean' in df.columns
    assert 'pc_std' in df.columns
    assert 'risk_reward' in df.columns
    
    aapl_over = df.loc[df['ticker'] == 'AAPL', 'over_pc'].values[0]
    assert aapl_over > 0 # prices increase as idx goes from 100 to 0 in our mock setup

def test_df_secind_tick_perf(mock_sqlite_db):
    ndays_range = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
    df = df_secind_tick_perf(ndays_range, ['AAPL', 'MSFT'])
    assert len(df) == 2
    assert 'sector' in df.columns
    assert 'industry' in df.columns
    assert df.loc[df['ticker'] == 'AAPL', 'sector'].values[0] == 'Technology'

def test_get_all_periods_ranked(mock_sqlite_db):
    df = get_all_periods_ranked()
    assert not df.empty
    assert 'Period' in df.columns
    assert 'risk_reward_rank' in df.columns
    assert 'rel_strength_ind' in df.columns
    assert 'prob_green_day_%' in df.columns
    
    # Check that cache is populated
    from portfolio.ticker_period_ranks_data import global_cache
    assert global_cache['df_all_periods'] is not None

def test_api_ticker_ranks_options(mock_sqlite_db):
    client = app.test_client()
    response = client.get('/data/ticker-ranks/options')
    assert response.status_code == 200
    data = response.get_json()
    assert 'sectors_industries' in data
    assert 'Technology' in data['sectors_industries']
    assert 'Consumer Electronics' in data['sectors_industries']['Technology']

def test_api_ticker_ranks(mock_sqlite_db):
    client = app.test_client()
    response = client.get('/data/ticker-ranks?period=Daily')
    assert response.status_code == 200
    data = response.get_json()
    assert len(data) >= 2
    assert data[0]['ticker'] in ['AAPL', 'MSFT']
    assert 'risk_reward_rank' in data[0]

def test_api_ticker_ranks_detail(mock_sqlite_db):
    client = app.test_client()
    response = client.get('/data/ticker-ranks/detail?ticker=AAPL')
    assert response.status_code == 200
    data = response.get_json()
    assert len(data) == 5
    assert data[0]['ticker'] == 'AAPL'
    assert 'Period' in data[0]
